name: ci

on:
  push:
    branches:
      - 'main'

env:
  TAG: ghcr.io/akiszka/signal-bot:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2.4.0
    - 
      name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - 
      name: Build the container image
      run: nix-build
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Load and publish image
      run: |
        docker load -i result
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u akiszka --password-stdin
        docker tag $(docker images --format "{{.ID}}" | head -n1) ${{ env.TAG }}
        docker push ${{ env.TAG }}

